FROM nvcr.io/nvidia/pytorch:20.03-py3

ARG DEBIAN_FRONTEND=noninteractive

#Install OpenCV dependencies
RUN apt-get update
RUN apt-get install -y libopencv-dev \
	               unzip zip 

# install these pip packages
RUN pip install Cython
RUN pip install tensorboard==1.15.0 \
    tensorboardX \
    jupyter-console \
    jupyterlab \
    ipywidgets \
    kubeflow-fairing \
    awscli \
    opencv-python==4.2.0.32\
    matplotlib \
    pycocotools \
    tqdm \
    pillow \
    jupyter-tensorboard

# install mlflow and mysql dependencies
RUN apt-get -y install libmysqlclient-dev
RUN pip install mlflow==1.7.0 mysql-connector-python mysqlclient


RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs

RUN npm install -g npm && \
    jupyter labextension install jupyterlab_tensorboard

WORKDIR /home



# include the following lines in your Dockerfile
EXPOSE 8888
ENV NB_PREFIX /
CMD ["sh", "-c", "jupyter lab --notebook-dir=/home --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}"]
